#define STRCOMPANYNAME	"Ados"
#define STRPRODUCTNAME	"BossGo"
#define STRREGAPPDATA	"Software\\Ados\\BossGo"
#define STRREGUNINSTALL	"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\BossGo"
#define STRCOPYRIGHT	"Copyright 2022 Ados Co., Ltd. All rights reserved."
